# Generated by Django 3.0.5 on 2020-12-13 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=70)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('ssn', models.CharField(default='', max_length=9)),
                ('smoking', models.BooleanField(default=False)),
                ('allergies', models.CharField(default='', max_length=170)),
                ('conditions', models.CharField(default='', max_length=170)),
            ],
        ),
        migrations.CreateModel(
            name='InsuredEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(default='', max_length=70)),
                ('billedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('coveredAmount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('policyHolderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyholders.PolicyHolder')),
            ],
        ),
    ]
